# Generated by Django 2.0.1 on 2021-11-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211110_1825'),
        ('posts', '0002_auto_20211111_0404'),
    ]

    operations = [
    ]
